EneanceTest.Application/Controllers/CategoryController.cs
using EneanceTest.Application.Dto;
using EneanceTest.Application.Entities;
using EneanceTest.Application.Models;
using EneanceTest.Application.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using EneanceTest.Application.ViewModel;
using EneanceTest.Application.Exceptions;

namespace EneanceTest.Application.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ILogger<CategoryController> _logger;
        private readonly ICategoryService _categoryService;

        public CategoryController(ILogger<CategoryController> logger, ICategoryService categoryService)
        {
            _logger = logger;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userCategories = await _categoryService.GetUserCategoriesAsync(userId);
            var viewModel = new CategoryViewModel() { Categories = userCategories };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(CategoryLight categoryLight)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var category  = new Category { Name = categoryLight.Name, UserId = userId };
            await _categoryService.CreateCategoryAsync(category);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(string categoryID)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var category = await _categoryService.GetCategoryByIdAndUserIdAsync(categoryID, userId);
                var viewModel = new UpdateCategoryViewModel() { Id = category.Id, Name = category.Name };
                return View(viewModel);
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    Message = ex.Message

                });
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost,ActionName("Update")]
        public async Task<IActionResult> UpdatePost(string categoryID, CategoryLight categoryLight)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var category = await _categoryService.UpdateCategoryAsync(categoryID, userId, categoryLight);
                var viewModel = new UpdateCategoryViewModel() { Id = category.Id, Name = category.Name };
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    Message = ex.Message

                });
            }
        }

        // it could be HttpDelete and use Form or Jquery request in Front, but no much time :)
        [HttpGet, ActionName("Delete")]
        public async Task<IActionResult> Delete(string categoryID)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                await _categoryService.DeleteCategoryAsync(categoryID, userId);
                return RedirectToAction("Index");

            }
            catch (Exception ex) 
            {
                return View("Error", new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    Message = ex.Message

                });
            }

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EneanceTest.Application/Controllers/JobController.cs
using EneanceTest.Application.Dto;
using EneanceTest.Application.Entities;
using EneanceTest.Application.Models;
using EneanceTest.Application.Service.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using EneanceTest.Application.ViewModel;
using EneanceTest.Application.Exceptions;

namespace EneanceTest.Application.Controllers
{
    [Authorize]
    public class JobController : Controller
    {
        private readonly ILogger<CategoryController> _logger;
        private readonly ICategoryService _categoryService;
        private readonly IJobService _jobService;


        public JobController(ILogger<CategoryController> logger, ICategoryService categoryService, IJobService jobService)
        {
            _logger = logger;
            _categoryService = categoryService;
            _jobService = jobService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userCategories = await _categoryService.GetUserCategoriesAsync(userId);
            var jobs = await _jobService.GetUserJobs(userId);


            var viewModel = new JobViewModel() 
            { 
                Categories = userCategories,
                Jobs = jobs
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(JobLight jobLight)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            try
            {
                var job = new Job()
                {
                    Name = jobLight.Name,
                    CategoryId = jobLight.CategoryId,
                    LimiteDate = jobLight.LimiteDate,
                    State = jobLight.State
                };

                await _jobService.CreateJobAsync(userId, job);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    Message = ex.Message

                });
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost,ActionName("Done")]
        public async Task<IActionResult> MakeJobStateDone(string jobId)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                await _jobService.MakeItDone(jobId, userId);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    Message = ex.Message

                });
            }
        }

        // it could be HttpDelete and use Form or Ajax request in Front, but no much time :)
        [HttpGet, ActionName("Delete")]
        public async Task<IActionResult> Delete(string jobId)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                await _jobService.DeleteJobAsync(jobId, userId);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return View("Error", new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    Message = ex.Message

                });
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EneanceTest.Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eneance Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EneanceTest.Application.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Category" asp-action="Index">Eneance Test</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="Index">Tasks</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Eneance Test
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>